server:
  port: 8899
spring:
  application:
    name: blog-server
  profiles:
    active: blog-dev
  redis:
    host: 162.14.77.8
    port: 6377
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://162.14.77.8:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 166056
  cloud:
    nacos:
      discovery:
        server-addr: 162.14.77.8:8848
