server:
  port: 8600
spring:
  application:
    name: gateway-server
  profiles:
    active: gateway-dev
  cloud:
    nacos:
      discovery:
        server-addr: 162.14.77.8:8848
        watch-delay: 5000
    gateway:
      discovery:
        locator:
          enabled: true
